# Generated by Django 6.0.7 on 2026-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_payment_method_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
